special_token_list = [
        'LocationOfAction',
        'HinderedBy',
        'HasFirstSubevent',
        'NotHasProperty',
        'NotHasA',
        'HasA',
        'AtLocation',
        'NotCapableOf',
        'CausesDesire',
        'HasPainCharacter',
        'NotDesires',
        'MadeUpOf',
        'InstanceOf',
        'SymbolOf',
        'xReason',
        'isAfter',
        'HasPrerequisite',
        'UsedFor',
        'MadeOf',
        'MotivatedByGoal',
        'Causes',
        'oEffect',
        'CreatedBy',
        'ReceivesAction',
        'NotMadeOf',
        'xWant',
        'PartOf',
        'DesireOf',
        'HasPainIntensity',
        'xAttr',
        'DefinedAs',
        'oReact',
        'xIntent',
        'HasSubevent',
        'oWant',
        'HasProperty',
        'IsA',
        'HasSubEvent',
        'LocatedNear',
        'Desires',
        'isFilledBy',
        'isBefore',
        'InheritsFrom',
        'xNeed',
        'xEffect',
        'xReact',
        'HasLastSubevent',
        'RelatedTo',
        'CapableOf',
        'NotIsA',
        'ObjectUse',
        'general Effect',
        'general React',
        'general Want',
        '[GEN]',
    ]

ASER_rel_2_NL = {
    'Co_Occurrence': "", # nothing
    'Conjunction': "and", 
    'Contrast': "but", 
    'Synchronous': "meanwhile",
    'Condition': "if", 
    'Reason': "because", 
    'Result': "so", 
    'Precedence': "before", 
    'Succession': "after",
    'Alternative': "or", 
    'Concession': "although", 
    'Restatement': "in other words", 
    'ChosenAlternative': "instead",
    'Exception': "except", 
    'Instantiation': "for example",
}

aser_r2id = {rel:i for i, rel in enumerate(ASER_rel_2_NL)}
aser_id2r = {i:rel for i, rel in enumerate(ASER_rel_2_NL)}

all_relations = [
        "xWant", "oWant", "general Want",
        "xEffect", "oEffect", "general Effect",
        "xReact", "oReact", "general React",
        "xAttr",
        "xIntent",
        "xNeed",
        "Causes", "xReason",
        "isBefore", "isAfter",
        'HinderedBy',
        'HasSubEvent',
    ] # Relations in CSKB Population

atomic18_relations = [
    'xAttr', 'xIntent', 'xNeed', 
    'xEffect', 'xReact', 'xWant',
    'oEffect', 'oReact', 'oWant'
]

CS_RELATIONS_2NL = {
    "AtLocation": "located or found at or in or on",
    "CapableOf": "is or are capable of",
    "Causes" : "causes",
    "CausesDesire": "makes someone want",
    "CreatedBy": " is created by",
    "Desires": "desires",
    "HasA": "has, possesses, or contains",
    "HasFirstSubevent": "begins with the event or action",
    "HasLastSubevent": "ends with the event or action",
    "HasPrerequisite": "to do this, one requires",
    "HasProperty": "can be characterized by being or having",
    "HasSubEvent" : "includes the event or action",
    "HinderedBy" : "can be hindered by",
    "InstanceOf" : " is an example or instance of",
    "isAfter" : "happens after",
    "isBefore" : "happens before",
    "isFilledBy" : "blank can be filled by",
    "MadeOf": "is made of",
    "MadeUpOf": "made up of",
    "MotivatedByGoal": "is a step towards accomplishing the goal",
    "NotDesires": "do not desire",
    "ObjectUse": "used for",
    "UsedFor": "used for",
    "oEffect" : "as a result, PersonY or others will",
    "oReact" : "as a result, PersonY or others feel",
    "oWant" : "as a result, PersonY or others want to",
    "PartOf" : "is a part of",
    "ReceivesAction" : "can receive or be affected by the action",
    "xAttr" : "PersonX is seen as",
    "xEffect" : "as a result, PersonX will",
    "xReact" : "as a result, PersonX feels",
    "xWant" : "as a result, PersonX wants to",
    "xNeed" : "but before, PersonX needed",
    "xIntent" : "because PersonX wanted",
    "xReason" : "because",
    "general Effect" : "as a result, other people or things will",
    "general Want" : "as a result, other people or things want to",
    "general React" : "as a result, other people or things feel",
    "gEffect" : "as a result, other people or things will",
    "gWant" : "as a result, other people or things want to",
    "gReact" : "as a result, other people or things feel",
}

num_of_triples_emnlp21 = {
    "xWant": 152634,
    "oWant": 59688,
    "gWant": 8093,
    "xEffect": 144799,
    "oEffect": 46555,
    "gEffect": 13529,
    "xReact": 100853,
    "oReact": 38581,
    "gReact": 4169,
    "xAttr": 152949,
    "xIntent": 59138,
    "xNeed": 98830,
    "Causes": 40450,
    "xReason": 320,
    "isBefore": 27784,
    "isAfter": 27414,
    "HinderedBy": 127320,
    "HasSubEvent": 16410
}